### ISSUE TITLE
Toast会被弹出的输入法遮住

### ISSUE THREAD

**Issue by xiaoqiang1999** [mochixuan/react-native-smart-tip#1]
**Toast会被弹出的输入法遮住**，而Snackbar是正常的会被弹出的输入法顶起。

**Comment by mochixuan** [comment]
Toast位置是根据高度设置的上中下，一般情况下Toast在输入法上也不合理吧。你可以选择
1. 当输入完，进行验证时，先调用Keyboard.dismiss()先把键盘隐藏再Toast，键盘隐藏应该300ms，Toast可以3000ms用户可以看的。
2. 当用户输入验证后，使用Toast,Position.CENTER，显示在中间或者Position.Top显示在头部。

**Comment by xiaoqiang1999** [comment]
看来您误解了我的意思。附件是这个问题的录屏，snackbar在输入法弹出时是正常的，而Toast有问题。还请修复。




------------------ 原始邮件 ------------------
发件人: "mochixuan"<notifications@github.com>;
发送时间: 2019年6月21日(星期五) 上午8:46
收件人: "mochixuan/react-native-smart-tip"<react-native-smart-tip@noreply.github.com>;
抄送: "最美的不是下雨天"<1362061285@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mochixuan/react-native-smart-tip] Toast会被弹出的输入法遮住 (#1)




Toast位置是根据高度设置的上中下，一般情况下Toast在输入法上也不合理吧。你可以选择
  
当输入完，进行验证时，先调用Keyboard.dismiss()先把键盘隐藏再Toast，键盘隐藏应该300ms，Toast可以3000ms用户可以看的。
 
当用户输入验证后，使用Toast,Position.CENTER，显示在中间或者Position.Top显示在头部。

**Comment by mochixuan** [comment]
这个不是bug，只是键盘的监听一盘插件是不会去做的，你可以看原生安卓Toast它是不会因为键盘显示，而太高自己位置。如果你不想隐藏键盘而提示用户的话，可以Position.Top。在组件里监听下就可以.

**Comment by xiaoqiang1999** [comment]
请看一下我给您私发的邮件附件，设置为center或top时确实有bug，toast会被剪掉一半


------------------ 原始邮件 ------------------
发件人: "mochixuan"<notifications@github.com>;
发送时间: 2019年6月21日(星期五) 下午2:27
收件人: "mochixuan/react-native-smart-tip"<react-native-smart-tip@noreply.github.com>;
抄送: "最美的不是下雨天"<1362061285@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mochixuan/react-native-smart-tip] Toast会被弹出的输入法遮住 (#1)




这个不是bug，只是键盘的监听一盘插件是不会去做的，你可以看原生安卓Toast它是不会因为键盘显示，而太高自己位置。如果你不想隐藏键盘而提示用户的话，可以Position.Top。在组件里监听下就可以.

**Comment by mochixuan** [comment]
看到了，我看看问题，谢谢提醒。

**Comment by xiaoqiang1999** [comment]
没关系。我觉得您的这个组件非常棒，还望修复。




------------------ 原始邮件 ------------------
发件人: "mochixuan"<notifications@github.com>;
发送时间: 2019年6月21日(星期五) 下午2:32
收件人: "mochixuan/react-native-smart-tip"<react-native-smart-tip@noreply.github.com>;
抄送: "最美的不是下雨天"<1362061285@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mochixuan/react-native-smart-tip] Toast会被弹出的输入法遮住 (#1)




看到了，我看看问题，谢谢提醒。

**Comment by mochixuan** [comment]
看了你发的视频，我这边是不会出现那种问题的，如果不是配置问题，可能就是机型问题，我里面加了横竖屏切换的兼容，里面也包含宽高变化时的兼容，你视频里demo键盘起来时屏幕高度=手机原屏幕高度-键盘高度了，监听使用的react-native监听。我想看看你demo里的安卓设置。

**Comment by mochixuan** [comment]
Tip: Android: 为防止键盘弹出时Toast被压缩,需改一个单词。
将 /android/src/main/AndroidManifest.xml 里的 windowSoftInputMode赋值为adjustPan
android:windowSoftInputMode="adjustPan"
原因是键盘压缩了屏幕的空间。
