### ISSUE TITLE
点击没有反应

### ISSUE THREAD

**Issue by Pisces-Fool** [mochixuan/react-native-smart-tip#12]
![image](https://user-images.githubusercontent.com/20684249/69410607-5dc0a700-0d46-11ea-8b26-4b501c3be319.png)
大佬，您好。我是直接把您的demo里的拿过来，但是没有效果也。是我少了什么吗，打过断点，Toast确实有这个对象，引用到了。但是就是没有tip弹出。

**Comment by mochixuan** [comment]
import {WToast} from 'react-native-smart-tip'

// Base 
show = () => {
	WToast.show({data: 'hello world'})
}

// Other
show = () => {
	const toastOpts = {
	    data: 'Success',
	    textColor: '#ffffff',
	    backgroundColor: '#444444',
	    duration: WToast.duration.LONG, //1.SHORT 2.LONG
	    position: WToast.position.TOP, // 1.TOP 2.CENTER 3.BOTTOM
	    icon: <Image source={require('../data/img/success.png')} style={{width: 32,height: 32,resizeMode: 'contain'}}/>
	}
	
	WToast.show(toastOpts)
}
你可以看下我的先看看能不能显示。如果能，那可能是你参数问题。
