### ISSUE TITLE
IOS下在Modal弹出来的基础上进行WModal.show弹不出来，Android下正常弹出

### ISSUE THREAD

**Issue by tlqylzn** [mochixuan/react-native-smart-tip#13]
// 这是具体弹框的代码
WModal.show({
        data: '请选择规格',
        position: WModal.position.CENTER,
        textColor: '#fff',
        backgroundColor: '#444444',
      });
      setTimeout(() => {
        WModal.hide();
      }, 1500);

**Comment by mochixuan** [comment]
首先非常抱歉，没有去验证iOS下的这个功能(以为用的比较少)，给你带了不便。
关于这个问题我查询和验证了一下。
参考一：https://github.com/facebook/react-native/issues/3445
参考二: https://stackoverflow.com/questions/38089530/react-native-modal-in-ios
经过自己的验证同时出现两个Modal是不被允许的在iOS。(验证版本: "react-native": "0.58.6")。现在根据资料可以暂时使用(已验证)，我会查找一种比较好的方式把这个功能弥补上。谢谢你提的这个Bug。

```
<Modal>
  <Text>A</Text>
  <Modal>
    <Text>B</Text>
  </Modal>
</Modal>

```

**Comment by tlqylzn** [comment]
我这边暂时到解决办法也是嵌套Modal，里面到Modal模拟toast，然后弹出后定时关掉，那我就先把这个issue关掉，期待你后续补上🙏

**Comment by 349989153** [comment]
没读懂啊，“经过自己的验证同时出现两个Modal是不被允许的”，然后又说“现在根据资料可以暂时使用(已验证)”

什么东西可以暂时使用？

**Comment by mochixuan** [comment]
两个Modal不允许的（iOS上）
<view>
  <Modal></Modal>
 <Modal></Modal>
</view>
所以我的ModalToast在iOS里是允许的。
但你可以实现
<view>
  <Modal>
    <Modal></Modal>
 </Modal>
</view>
