### ISSUE TITLE
为什么我的一点反应没有

### ISSUE THREAD

**Issue by chuhouyi** [mochixuan/react-native-smart-tip#15]
我下载了demo运行，也新建了项目把这个组件添加进来，为什么点击没反应

**Comment by mochixuan** [comment]
没有遇到过这个问题。你的在什么设备上运行的，设备型号和版本多少。

**Comment by chuhouyi** [comment]
> 没有遇到过这个问题。你的在什么设备上运行的，设备型号和版本多少。

大神你好，我在react-native0.61.5版本上运行的demo，我今天把背景颜色改成了rgb格式就好了，之前的十六进制颜色不显示，可能是我这边的问题

**Comment by mochixuan** [comment]
也可能是0.61版本对颜色或者透明颜色属性不支持了。谢谢提醒。我有时间看下。感谢。
