### ISSUE TITLE
可以升级下react-native-root-siblings版本，来解决无法显示的问题

### ISSUE THREAD

**Issue by bashen1** [mochixuan/react-native-smart-tip#16]
RT，react-native-root-siblings已经升级到4.0.6，升级下依赖来解决模块无法显示的问题

**Comment by mochixuan** [comment]
可以。能说下。什么模块无法显示吗

**Comment by bashen1** [comment]
WSnackBar、WModal、WToast
因为好想这三个组件都用到了new RootSiblings

**Comment by mochixuan** [comment]
好的，我看下。测试一下。没问题下午就更新下

**Comment by mochixuan** [comment]
我测试了一下"react": "16.9.0" 、 "react-native": "0.61.5"插件运行正常。react-native-root-siblings最新版没有比较大的改变。所以暂时不升级版本。
