### ISSUE TITLE
How to smooth transition from loading to success with Toast component?

### ISSUE THREAD

**Issue by xjf348060793** [mochixuan/react-native-smart-tip#18]
When I use  suceess  or  fail  to kill the loading, i just wanna replace the icon, not  the whole toast, how can i do that?

**Comment by mochixuan** [comment]
You can record the text of the prompt and rewrite it in the next update.

**Comment by xjf348060793** [comment]
![shining](https://user-images.githubusercontent.com/22151955/76814837-dcca7580-6836-11ea-9592-f0b023433c3f.gif)

**Comment by xjf348060793** [comment]
The toast only exposed two api,  show and hide,   i saw the source code,  invoke show will   
kill the old rootSiblings  and  build new rootSiblings, that caused Screen wobble。

**Comment by mochixuan** [comment]
Wait a minute, let me see if I can add a method, I understand what you mean

**Comment by mochixuan** [comment]
两个Toast同时显示会出现重叠，所以我这个设计的时候一个时间段自能显示显示一个Toast。你可以注释调这行代码[Hide](https://github.com/mochixuan/react-native-smart-tip/blob/39cec7f4fc07f1369f258ee643efa1237c0a0cad/lib/toast/Toast.js#L22)。

**Comment by xjf348060793** [comment]
3Q
