### ISSUE TITLE
有个警告错误

### ISSUE THREAD

**Issue by jackieit** [mochixuan/react-native-smart-tip#20]
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false` 
    in SnackView (at SnackBar.js:25)

最新的0.62版本。

**Comment by mochixuan** [comment]
谢谢提醒。我把这个属性加上useNativeDriver={false}.

**Comment by mochixuan** [comment]
Fix react-native@0.62.2 useNativeDriver attribute reminder
