### ISSUE TITLE
WSnackBar close suggestion

### ISSUE THREAD

**Issue by sandersonsoares** [mochixuan/react-native-smart-tip#21]
I would like to leave it as a suggestion: An option to slide to close in SnackBar mode, or to click on the component and close.

The suggestion was to close it, invoking the `.hide()` method, but it could be a customizable action property as well.

Yes, I know you have a similar option, but it is using text. The ideal would be one executed from the interaction of any area of ​​the component. Using only `WSnackBar.show()`.

**Comment by mochixuan** [comment]
Thank you very much for your proposal, I will add sliding interaction later

**Comment by mochixuan** [comment]
The sliding hide function has been added
