### ISSUE TITLE
how to set no Admission animation?

### ISSUE THREAD

**Issue by lx495707690** [mochixuan/react-native-smart-tip#22]
how to set no Admission animation?

**Comment by mochixuan** [comment]
Without this design, it is temporarily impossible to achieve. You can change it yourself, the time of the entrance animation is equal to 0

**Comment by lx495707690** [comment]
ok thanks!

**Comment by lx495707690** [comment]
> Without this design, it is temporarily impossible to achieve. You can change it yourself, the time of the entrance animation is equal to 0

ok thanks!
