### ISSUE TITLE
inEasing not working for android 

### ISSUE THREAD

**Issue by girish54321** [mochixuan/react-native-smart-tip#25]
inEasing not working in android (debug) not tested in APK

` data: "",
      textColor: "#ffffff",
      backgroundColor: error ? "#ff490b" : CONST.APP_COLOR,
      duration: WToast.duration.LONG, 
      position: WToast.position.BOTTOM, 
      isShowShadow: false,
      inEasing: Easing.ease,`

**Comment by mochixuan** [comment]
You can try Easing.inOut(Easing.ease)，If react-native can be achieved, this can certainly be achieved

**Comment by girish54321** [comment]
@mochixuan  No not working man / woman 
but IOS works..  
android not working....

**Comment by mochixuan** [comment]
inEasing: Easing.ease is allowed on Android phones (Xiaomi 6), what is your phone model

**Comment by girish54321** [comment]
@mochixuan Samsung A9 pro (2016) 
but no problem snack bar works nicely.
Thanks...
