### ISSUE TITLE
Disable SnackBar ellipsis and show full text message

### ISSUE THREAD

**Issue by girish54321** [mochixuan/react-native-smart-tip#27]
Hi my friend
i want to show full text message but show only some part of text and other is like "..." can you help me with that
![20200714_120010](https://user-images.githubusercontent.com/47414322/87392240-ca383100-c5c9-11ea-889e-51f1a0722a1d.jpg)

**Comment by mochixuan** [comment]
I have added an attribute numberOfLines to Snackbar, the default is equal to 1, you can modify it to 10 or greater. This is the parameter that limits the maximum number of rows. In the latest version 2.2.1

**Comment by girish54321** [comment]
Thanks @mochixuan works very nicely 

`numberOfLines: 3`

closing this issue..
