### ISSUE TITLE
你好，data 内容可以传入组件吗

### ISSUE THREAD

**Issue by Paul0523** [mochixuan/react-native-smart-tip#29]
像是snack bar , 用来做弹出浮层

**Comment by mochixuan** [comment]
这个暂时不可以。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mochixuan/react-native-smart-tip"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月3日(星期一) 下午3:08
收件人:&nbsp;"mochixuan/react-native-smart-tip"<react-native-smart-tip@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[mochixuan/react-native-smart-tip] 你好，data 内容可以传入组件吗 (#29)





 
像是snack bar , 用来做弹出浮层

**Comment by mochixuan** [comment]
这个功能我有个时间可以加上去
