### ISSUE TITLE
显示toast和modal的时候，能否有一个显示mask遮罩层的选项？

### ISSUE THREAD

**Issue by joket1999** [mochixuan/react-native-smart-tip#30]
发现在显示toast或者modal时，没有遮罩层，容易误触，能否加一个

**Comment by mochixuan** [comment]
显示Modal时是不会误触的，这个可以加个熟性就可以，由于原生的Android的Toast被设计时也是不会遮盖下层的触摸。
插件源码里有pointerEvents熟悉你可以改下就好。
来自网络pointerEvents
none 发生在本组件与本组件的子组件上的触摸事件都会交给本组件的父组件处理.
box-none 发生在本组件显示范围内,但不是子组件显示范围内的事件交给本组件,在子组件显示范围内交给子组件处理
box-only 发生在本组件显示范围内的触摸事件将全部由本组件处理,即使触摸事件发生在本组件的子组件显示范围内
auto 视组件的不同而不同,并不是所有的子组件都支持box-none和box-only两个值,使用时最好测试下

**Comment by joket1999** [comment]
> 显示Modal时是不会误触的，这个可以加个熟性就可以，由于原生的Android的Toast被设计时也是不会遮盖下层的触摸。

我查看了代码，ToastView.js
![image](https://user-images.githubusercontent.com/6611880/92445799-7885de80-f1e7-11ea-9942-24f71184478a.png)

其实已经有一个透明的遮罩层，但是带有了pointerEvents="none"，所有onPress都穿透了遮罩层。不知道是否故意这么设计

**Comment by mochixuan** [comment]
原生的Toast是不会遮盖任何触摸的，所以设计的时候也是设计成不遮盖触摸，毕竟Toast理念就是提示
