### ISSUE TITLE
如何改变提示文字大小呢？

### ISSUE THREAD

**Issue by benchenchuang** [mochixuan/react-native-smart-tip#36]
请问可以开放一个接口 改变WToast.show()中提示文字大小嘛？

**Comment by mochixuan** [comment]
可以，但可以要等我有时间才行。你可以直接改  https://github.com/mochixuan/react-native-smart-tip/blob/41f6873586633198a72860a03914f3001dfec1d1/lib/toast/ToastView.js#L172 。这样更快。
