### ISSUE TITLE
RN 0.64 首次初始化程序无法使用 ModalShowToast

### ISSUE THREAD

**Issue by zhushenwudi** [mochixuan/react-native-smart-tip#45]
"dependencies": {
    "react": "17.0.1",
    "react-native": "0.64.1",
    "react-native-smart-tip": "^2.3.0"
  }

猜测0.64做了很多改动。建议全部升到最新版

ios 和 android 均可复现：

demo 链接：
链接: https://pan.baidu.com/s/1VT9Dv0AVfDo86VxplYIWAw  密码: 6ogc

demo 使用：
yarn install
cd ios
pod install --verbose --no-repo-update
yarn ios

**Comment by mochixuan** [comment]
import { WModalShowToastView } from 'react-native-smart-tip'
应该如上导入测试你的demo可以运行改完后

**Comment by zhushenwudi** [comment]
> import { WModalShowToastView } from 'react-native-smart-tip'
> 应该如上导入测试你的demo可以运行改完后

3q,已经可以了。
