### ISSUE TITLE
WToast会被Modal挡住

### ISSUE THREAD

**Issue by huangsong** [mochixuan/react-native-smart-tip#7]
当使用Modal组件的时候，WToast会被挡在下面。

**Comment by huangsong** [comment]
`<Modal
                            animationType={'fade'}
                            transparent={true}
                            visible={withdrawSuccessTipsVisible}
                            style={{flex:1}}>
                            <KeyboardAvoidingView behavior={'height'} style={{flex: 1}}>
                        <View style={GlobalStyles.modalBox}>
                            <TouchableOpacity
                                onPress={()=>{
                                    this.setState({
                                        withdrawSuccessTipsVisible:false
                                    })
                                }}
                                style={GlobalStyles.modalCloseTouch}>

                            </TouchableOpacity>
                            <View style={[GlobalStyles.modalForm,styles.withdrawTips]}>
                                
                                <View style={[GlobalStyles.modalFormBody,{alignItems:'center'}]}>
                                    <TouchableOpacity
                                        onPress={()=>{
                                            Clipboard.setString(Config.serviceWX);
                                            WToast.show({
                                                position: WToast.position.CENTER,
                                                data: '成功复制微信号到剪切板，请到微信中搜索添加!'
                                            })
                                        }}
                                    >
                                        <FontAwesome
                                            name={'weixin'}
                                            style={{fontSize:50,color:'#1aac19',marginLeft:35}}
                                        />
                                        <View style={[GlobalStyles.flexRow,{alignItems:'center'}]}>
                                            <Text style={{fontSize:22,fontWeight:'bold',color:'#000'}}>{Config.serviceWX}</Text>
                                            
                                        </View>

                                    </TouchableOpacity>

                                </View>
                               
                            </View>
                        </View>
                            </KeyboardAvoidingView>
                        </Modal>`

**Comment by mochixuan** [comment]
这样讲吧：在安卓里Model层级比Activity高，Activity就是存放RN的地方，意思是Model最上层，所以RN组件和代码都会被遮住，你可以看看网上其他人的这个是避免不了，你可以使用WModel试试。要记得自己取消
