### ISSUE TITLE
怎么集成全局Toast

### ISSUE THREAD

**Issue by wowtrxqn** [mochixuan/react-native-smart-tip#8]
老大，想把你插件里的Toast集成到全局

![123123213123](https://user-images.githubusercontent.com/24369118/65398290-e378b280-dde8-11e9-8c7a-c451d30fb280.png)

全局Loading我集成好了，好像直接用你写的Toast不行

**Comment by mochixuan** [comment]
Toast的实现是基于react-native-root-siblings，它里面也用到AppRegistry.setSw.....。我没有像你这样写过，你说的全局指的是那块的全局？原生加RN的全局？还是纯RN，纯RN，可以按照我的Demo那种方式写。

**Comment by wowtrxqn** [comment]
> Toast的实现是基于react-native-root-siblings，它里面也用到AppRegistry.setSw.....。我没有像你这样写过，你说的全局指的是那块的全局？原生加RN的全局？还是纯RN，纯RN，可以按照我的Demo那种方式写。

现在我的组件内调用loading动画 直接写Load.show() 就可以，，我也想随便在哪调用Toast.show()，不用在组件内再引用toast模块

**Comment by wowtrxqn** [comment]
> Toast的实现是基于react-native-root-siblings，它里面也用到AppRegistry.setSw.....。我没有像你这样写过，你说的全局指的是那块的全局？原生加RN的全局？还是纯RN，纯RN，可以按照我的Demo那种方式写。

我的全局是指挂到global 上的意思，，你的插件很棒，能不能像我这样直接写，集成到global上？

**Comment by mochixuan** [comment]
还是没太明白，我平时开始是Util工具类把showToast封装下，其他的地方引用后直接showToast(data)就可以调用了，你想要实现的全局调用好像也是这个吧。这个Toast不要包装在组件里面。

**Comment by wowtrxqn** [comment]
> 还是没太明白，我平时开始是Util工具类把showToast封装下，其他的地方引用后直接showToast(data)就可以调用了，你想要实现的全局调用好像也是这个吧。这个Toast不要包装在组件里面。

我再看看，谢谢老大

**Comment by wowtrxqn** [comment]
> 还是没太明白，我平时开始是Util工具类把showToast封装下，其他的地方引用后直接showToast(data)就可以调用了，你想要实现的全局调用好像也是这个吧。这个Toast不要包装在组件里面。

可以了，，是我引用错了了，我刚看到，我写了{}，你写的是export default
